rubocop:
  enabled: false

coffeelint:
  enabled: false

jshint:
  enabled: false

hamllint:
  enabled: false

golint:
  enabled: false

swiftlint:
  enabled: false

phpcs:
  enabled: true

eslint:
  enabled: true

scss-lint:
  enabled: false

sass-lint:
  enabled: true
  config_file: .sass-lint.yml
