rules:

  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 1
  no-ids: 0
  no-important: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-domains: 0
  no-url-protocols: 0

  # Nesting
  declarations-before-nesting: 2

  # Name Formats
  class-name-format: 1
  function-name-format: 0
  id-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  attribute-quotes: 2
  border-zero: 1
  clean-import-paths: 2
  hex-length: 0
  hex-notation: 2
  leading-zero: 0
  nesting-depth: 0
  pseudo-element: 2
  quotes: 2
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 2
  brace-style:
    - 1
    -
    style: 'stroustrup'
  indentation:
    - 2
    - size: 4

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 1
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
